---
title: "Draft Quarto document"
author: "Your Name"
format: html
editor:
    markdown: 
      wrap: 72
      canonical: true
---

# Advance learnig objectives

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = TRUE)

targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(recipes)
lipidomics <- tar_read(lipidomics)
source(here::here("R/functions.R"))
```

# 6. Descriptive results using targets

```{r}
tar_read(df_stats_by_metabolite) %>%
    mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
    select(Metabolite = metabolite, "Mean SD" = MeanSD) %>%
    knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r}
tar_read(fig_metabolite_distribution)
```

# 7. A general approach to do analysis

## Transforming into wideformat

```{r pivot data to wide format}
lipidomics_wide <- lipidomics %>%
    column_values_to_snake_case(metabolite) %>%
    metabolites_to_wide()
```

Predictors, outcome, standardization...

Combine everything and the two parts in the input by pipeline,
separately.

## Run analysis and get estimates!

```{r mode workflow combined in one}
create_model_workflow(
    parsnip::logistic_reg() %>%
        parsnip::set_engine("glm"),
    lipidomics_wide %>%
        create_recipe_spec(metabolite_cholesterol)
) %>%
    parsnip::fit(lipidomics_wide) %>%
    tidy_model_output()
```

# 8. Now fun start: make multiple regresiion in one go

```{r}
model_estimates <- lipidomics %>% 
 split_by_metabolite() %>% 
    purrr::map(generate_model_results) %>% 
    list_rbind() %>% 
     dplyr::filter(stringr::str_detect(term, "metabolite_"))
```

```{r}
lipidomics %>% 
    mutate(term = metabolite) %>% 
    column_values_to_snake_case(term) %>% 
    mutate(term = str_c("metabolite_", term)) %>% 
    distinct(term, metabolite) %>% 
    right_join(model_estimates, by = "term")
```

```{r}

```

```{r}
model_1<- calculate_estimates(lipidomics)
```
